uint8 BAT_CMD_BOTH_OFF=1
uint8 BAT_CMD_DISCHARGE_ON=2
uint8 BAT_CMD_DISCHARGE_OFF=3
uint8 BAT_CMD_CHARGE_ON=4
uint8 BAT_CMD_CHARGE_OFF=5
uint8 BAT_CMD_BOTH_ON=6
uint8 BAT_CMD_CHARGE_FAULT=7
uint8 BAT_CMD_CHARGE_FAULT_W_DISCHARGE=8
uint8 command
---