# Sub-message of DVL "DopplerVelocity.msg"

# low-latency trigger flag
uint32 cx
# bottom track pings per ensemble
uint32 bp
# water profile pings per ensemble
uint32 wp
# number of bins
uint32 wn
# bin spaging [cm]
uint32 ws
# transmit length [cm]
uint32 wt
# blank after transmit [cm]
uint32 wf
# false target threshold
uint32 wa
# low correlation threshold
uint32 wc
# error correlation threshold
uint32 we
# data out flags
uint32 wd
# clip past bottom flag
uint32 wi
